name: Nest.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: backend
      #     push: true
      #     tags: |
      #       ghcr.io/romicusblr/backend:latest

      - name: 'Build Inventory Image'
        run: |
          docker build --tag ghcr.io/romicusblr/backend:latest backend
          docker push ghcr.io/romicusblr/backend:latest
